# Generated by Django 3.2.6 on 2021-10-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category'),
        ),
    ]
